### ISSUE TITLE
Make "load and fill word doc" function

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#11]
Could include an array of variables as a parameter, along with a file path and a name of the form to be filled out.

**Comment by RobertFewins-Kalb** [comment]
Hey @theVKC  @levesswe, here's a thing -- I've been poking around with LPShanley's Agency Custom script and have modified it to look for .docx, .dotx, and .dotm files. Using @levesswe suggestion, I have built an Excel file that stores all the file names and form field names associated with specific values to be pulled from PRISM...

![image](https://cloud.githubusercontent.com/assets/7842016/13475907/e1c6100e-e08a-11e5-97e3-d82fa2550b71.png)


It turns out Anoka has 600 Word docs that need updating with form fields to make this fully operational. However, the architecture is there.

**Comment by theVKC** [comment]
See https://github.com/MN-Script-Team/BZS-FuncLib/issues/234. I am hoping to wrap this one up this month. I'd like to get it documented in time for some MAXIS changes taking place over the summer, and PRISM could hopefully use it.

**Comment by theVKC** [comment]
OK all, I'm closing this issue because it's tied to https://github.com/MN-Script-Team/BZS-FuncLib/issues/234, and now that we're all merging functions together, this would constitute a duplicate issue. Function issues should be moved to FuncLib.
