### ISSUE TITLE
Date of the Hearing - Judicial

### ISSUE THREAD

**Issue by paschell** [MN-CS-Script-Team/PRISM-Scripts#14]
Several users reported an error when trying to use this script, I tried several times and recd same error.

 Script Error at Line 1, Column1:
 Object not a collection

**Comment by theVKC** [comment]
This is happening because the global variables file you have doesn’t contain the array of attorneys. I’ll email you the code to include in the Q:\ Global Variables file.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by levesswe** [comment]
@theVKC states she resolved this issue.

**Comment by KallistaImdieke** [comment]
I have received notice that we are receiving this same error: 
Script Error at Line 1, Column1:
Object not a collection

for the Note-contempt hearing and the Note- Hearing Note Scripts.  

Thanks!

**Comment by theVKC** [comment]
I'm going to take a guess and say you don't have an array of attorneys. You can probably resolve it by creating one. Your global variables file should have several attorneys in it in an array. If it doesn't, we should discuss how to get one set up for you.

**Comment by theVKC** [comment]
And no, I don't think this should be reopened, since I'm pretty sure it's not a problem related to the actual script, but rather to a global variable setup.

**Comment by KallistaImdieke** [comment]
I think this is something that only Gay is able to do for us I emailed her to check it out.

Thanks!

**Comment by theVKC** [comment]
If she has any questions on what she sees, @GayS can email me!
