### ISSUE TITLE
Unreimb/Unins Docs

### ISSUE THREAD

**Issue by TammyStearns** [MN-CS-Script-Team/PRISM-Scripts#222]
I ran this script and discovered it creates DORD doc F0659, however, it shows up as incomplete.  When running the script, I put the PERCENT amount in the script box but it did not add the PERCENT amount in the DORD document - therefore, the document was left as Incomplete.

**Comment by levesswe** [comment]
Tammy, are you able to replicate this issue on the same case and/or other cases?  I am having trouble replicating the problem you are reporting.  Did you see the msgbox that appears to prompt for you to select the legal heading, and click OK after you selected the legal heading? I seem to remember something about some updated versions of PRISM not allowing users to do anything in PRISM while the message box is open, and wonder if that may be the issue here.

**Comment by TammyStearns** [comment]
I will test it out again today and let you know.

Thanks.

**Comment by gretchent74** [comment]
I think I discovered the problem and will update it soon.

**Comment by levesswe** [comment]
This should be resolved.  Closing issue.
