### ISSUE TITLE
BULK - Review Continued Interest Suppression

### ISSUE THREAD

**Issue by levesswe** [MN-CS-Script-Team/PRISM-Scripts#259]
BUG: change the date range of payments to be based on the last complete month rather than the last 90 calendar days.

**Comment by theVKC** [comment]
Same as the other one. Any takers on this one? Is this a priority? @MN-CS-Script-Team/scriptwriters?

If nobody wants it by hackathon, I will close the issue.

**Comment by wrightcountykaren** [comment]
I do not recall the “issue” with the script.  I do think it is a GREAT script idea and it shouldn’t be closed.  I’m not sure that I totally understand the comments that are listed under the issue on GitHub.  Maybe it is something that could be talked out in more detail at the hackathon in order to define what the script would actually do and then someone could start writing it?

Karen Popken
Wright County Child Support Supervisor
Phone: 763-682-7403
How did I do today? Click here to complete our customer service survey.<https://www.surveymonkey.com/r/WCHHS_CSS>

**Comment by paschell** [comment]
This script needed enhancements.  The current script 'as is' runs the script using incorrect dates.  So depending on the day you run it, the non-custodial parent may or may not be compliant.   In our testing, several cases brought the date issue to light.  The suggestion for enhancement was to use a defined date range.  Also to add a box to send the DORD docs, if appropriate.   This is a Wendy script and it is on her list to fix the dates and add the docs.

**Comment by theVKC** [comment]
I see, @paschell. I am a bit thrown off because it doesn't say "bug" or "problem" or "incorrect" in the description. Generally bugs are always worked at one-point-or-another, and if nobody else takes it, I guess I would. But, if Wendy has this on her list (she wasn't assigned), I'll assign to her and we'll await her return. :)

**Comment by paschell** [comment]
I believe that some think it works good enough.    This script has a problem.  To me, it is a BUG/problem  as it does not adhere to DHS policy for the 90 day review of timely payments.  The date function should calculate payments from the 1st of the month through the end of the month for the past 90 days.  It should not go back 90 days from the day you run the script as depending on the day the obligor may or may not be compliant. To be consistent with other review processes it should be checking the last full month reported and then back a total of 90 days.  I hope I explained this well enough.  I still have the written testing evaluation.

**Comment by theVKC** [comment]
I agree completely, this sounds an awful lot like it should have been considered a "bug" and not an "enhancement". I have on my things-to-discuss-with-counties list a general description of what's different between these. Here's a rundown:

* Enhancement: a "nice-to-have" feature that should be added, but that we can live without.
* Bug: it's currently wrong and should be righted.

**Comment by levesswe** [comment]
LOL, the ability to send out the DORD docs is an enhancement, issue with the date is a bug.  So this issue is listing both - perhaps they should be separate?

**Comment by theVKC** [comment]
They should be. Can you create a separate issue around the enhancement? Also, do you have an ETA on when you can complete the bug portion? I'd break freeze to get bugs through at this point, I think,

**Comment by levesswe** [comment]
I haven't put any time into this script recently, and have no ETA.  I am playing catch-up after a few days off...  If you think you will have time before I will, feel free to steal.

**Comment by theVKC** [comment]
I'll mark it as help-wanted and we can look at it at hackathon. If you could create the second issue for the enhancement, that'd be swell.

**Comment by levesswe** [comment]
See #402

**Comment by theVKC** [comment]
Thank you!

**Comment by theVKC** [comment]
#407 is replacing this one.
