### ISSUE TITLE
CAAD for Postal Verification

### ISSUE THREAD

**Issue by glorialink** [MN-CS-Script-Team/PRISM-Scripts#264]
In Washington County, we are supposed to provide a detailed FREE note upon the receipt of postal verification with specific information and in a specific format.  Would like to create a template that would copy information from NCDD/CPDD and enter into CAAD.

**Comment by theVKC** [comment]
@jmarieraymond, can I get an update on this one?

**Comment by jmarieraymond** [comment]
I think this one is good to go, I will just wait until Friday’s meeting with Veronica before adding to Github.

**Comment by theVKC** [comment]
Same as #262, Jessica. You're only being "unassigned" because of a quirk in how GitHub works when I set someone to inactive (you're inactive because you've had no code pulled in six months, this will be easily resolved once you send your work in). Trust me, you are still very much the go-to-gal for this issue. :)

**Comment by theVKC** [comment]
@jmarieraymond, can I get an update on the status of this issue? Did you get your script work completed? If you would like help getting it on GitHub, I'd be happy to oblige. :) Just let me know!!

**Comment by jmarieraymond** [comment]
Arg, I don't even know what I did with it and it probably isn't really that helpful, we can close it out. Thanks!

**Comment by theVKC** [comment]
I'll close for now, @jmarieraymond, but I'm marking it as a "sleeper", meaning we can reopen it if there's interest. If you find your files and want to revisit it, just let me know!!
