### ISSUE TITLE
MAXIS FuncLib is causing problems for scripts restructure

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-CS-Script-Team/PRISM-Scripts#319]
In MAXIS FuncLib, there is code: county_name = ""

This is reseting the county name field and inhibiting counties from setting their own main menus.

**Comment by theVKC** [comment]
Hi @RobertFewins-Kalb... could we not work our same logic from MAXIS scripts into the PRISM scripts, and get county info on demand if it isn't specified?

Alternatively, I'd be open to adding functionality to only reset this if global variables for PRISM didn't already set it.

I just don't want to see PRISM scriptwriters losing access to MAXIS-driven changes, nor do I want to see redundancy created by separating the projects (requiring PRISM admins to monitor BZS-FuncLib and copy relevant changes over, and vice versa). Surely amending our functionality to accommodate PRISM script differences is more reasonable than disconnecting entirely from our FuncLib.

**Comment by theVKC** [comment]
It's not a current functionality issue, it's a future functionality issue. Let's futureproof by moving toward a single FuncLib. Especially since DHS is hiring a PRISM scriptwriter.

`IF county_name <> ""` breaks functionality with older MAXIS GlobVars, because I intentionally want to override counties setting this manually (see `get_county_code`, which also helps in scriptwriters and multi-county agencies such as tribal work or conglomerations). I'm more inclined to do something such as `IF [some_PRISM_specific_variable] <> "" THEN county_name = ""` so that way we can retain both sets of functionality. I'm guessing PRISM GlobVar or FuncLib has something PRISM-specific that can be pulled through in this way.

**Comment by RobertFewins-Kalb** [comment]
It is a current functionality issue because currently PRISM scripts don't work as intended when calling MAXIS FuncLib. I'm also trying to maintain stability for PRISM script writers but not asking them to modify their agency's global variables file again.

**Comment by theVKC** [comment]
I don't think you'd have to. I think if you add a variable to the PRISM FuncLib (`PRISM_FuncLib_run = true` for example), then agency GlobVar does not require an update and the supported FuncLib can take that functionality and work with it. Eventually as integration progresses, I foresee offering unified GlobVar to reduce work needed for county admins to go live on scripts.

In any case, my suggestion allows you to continue benefiting from our supported FuncLib and doesn't break functionality, thus fulfilling your statement "If MAXIS FuncLib doesn't break the restructure, then I can totally see adding it back.".

**Comment by theVKC** [comment]
I'll even push it through the release cycle so it's live in release. I'd just hate to see this connection broken. It increases redundancy for script admins to separate the two.
