### ISSUE TITLE
Pay or Report Note Script

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-CS-Script-Team/PRISM-Scripts#365]
I attempted to use this script and received the following error message 

"Script Error at Line 1, Column 1: path not found"

Not sure why this is.  I closed prism and reopened it and am still having it. 

thanks!

**Comment by theVKC** [comment]
@KallistaImdieke, this happens when a script cannot find a Global Variables file. @RobertFewins-Kalb appears to have resolved the issue.

You may want to consider asking IT for approval to install GitHub Desktop. I'd be happy to show everyone how to use it at the next hackathon. There's MAXIS-centric documentation that pretty much explains it as well, that's on SIR.
